---
title: "Arima Final Version"
output: html_notebook
---


```{r}
library(dplyr)
library(ggplot2)
library(lubridate)  

df <- read.csv('/Users/kamilpacana/Desktop/DS4420/Project/train.csv')
df_filtered <- df[df$Store == 1, ]
df_filtered <- df_filtered[, c("Date", "Sales"), drop = FALSE]
df_filtered <- na.omit(df_filtered)
df_filtered$Date <- as.Date(df_filtered$Date)
sales <- df_filtered[order(df_filtered$Date),]


df_weekly <- summarize(
  group_by(
    mutate(
      df_filtered, Week = floor_date(Date, "week")), 
    Week), 
  Sales = sum(Sales)
)


ggplot(df_weekly, aes(x = Week, y = Sales)) +
  geom_line() +
  ggtitle('Weekly Sales History') +
  xlab('Year') +
  ylab('Sales') +
  theme_minimal()


```
```{r}
decomp1 <- decompose(ts(df_weekly$Sales, frequency = 52), type = "additive")
plot(decomp1)
```

```{r}
acf(df_weekly$Sales, main = "Sales ACF Plot", lag.max=52)
```
```{r}
pacf(df_weekly$Sales, main = "Sales PACF Plot", lag.max=52)
```



```{r}
library(forecast)

train_size <- round(0.8 * nrow(df_weekly))
train_data <- df_weekly[1:train_size,]
test_data <- df_weekly[(train_size + 1):nrow(df_weekly),]
y_train <- train_data$Sales
y_test <- test_data$Sales


freq <- 52
sales_ts <- ts(y_train, frequency = freq)


sarima_mod_auto <- auto.arima(sales_ts, seasonal = TRUE)
sarima_forecast <- forecast(sarima_mod_auto, h = length(y_test))


sarima_pred_data <- data.frame(
  Week = test_data$Week, 
  Sales = as.numeric(sarima_forecast$mean)
)


plot(test_data$Week, test_data$Sales, type = "l", col = "blue", lwd = 2, 
     xlab = "Week",  ylab = "Sales", main = "SARIMA Model Predictions", xaxt="n")
lines(sarima_pred_data$Week, sarima_pred_data$Sales, col = "red", lwd = 2, lty = 2)
legend("topleft", legend = c("Actual Sales", "SARIMA Predicted Sales"), 
       col = c("blue", "red"), lty = c(1, 2), bty = "n")
date_ticks <- seq(min(test_data$Week), max(test_data$Week), by = "4 weeks")
axis(1, at = date_ticks, labels = format(date_ticks, "%b %d"))

sarima_pred <- sarima_pred_data$Sales
sarima_mae <- mean(abs(y_test - sarima_pred))
sarima_rmse <- sqrt(mean((y_test - sarima_pred)^2))
sarima_r2 <- 1 - sum((y_test - sarima_pred)^2) / sum((y_test - mean(y_test))^2)



cat("SARIMA Model Performance:\n")
summary(sarima_mod_auto)
cat(sprintf("Mean Absolute Error (MAE): %.2f\n", sarima_mae))
cat(sprintf("Root Mean Squared Error (RMSE): %.2f\n", sarima_rmse))
cat(sprintf("R-squared (R²): %.4f\n", sarima_r2))
```

```{r}
plot(test_data$Sales, sarima_pred_data$Sales, col = "blue", lwd = 2, 
     xlab = "Actual Weekly Sales", ylab = "Predicted Weekly Sales", main = "Predicted Weekly Sales vs. Actual Weekly Sales")
abline(a = 0, b = 1, col = "red", lwd = 2, lty = 2)



```


